# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ciphercode < Formula
  desc ""
  homepage "https://github.com/Lachignol/cipherCode-cli"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Darwin_x86_64.tar.gz"
      sha256 "e6448740029104d05e1c6775c45470a786c7efa38f43e9feb8c3a1f181acd8ce"

      def install
        bin.install "cipherCode"
      end
    end
    on_arm do
      url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Darwin_arm64.tar.gz"
      sha256 "262c07f41d0a35d995f36472de99a44564ede0023cf8a7a20cc16bcd9518f3b0"

      def install
        bin.install "cipherCode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Linux_x86_64.tar.gz"
        sha256 "1b0ae292c76a6c2df00dad395d22a9e8dd3c46c7f2728597eeafa2ab6f414c2e"

        def install
          bin.install "cipherCode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Linux_arm64.tar.gz"
        sha256 "46fbb3f8d8f6e9f9a38337afdd72ac25c87456ad94bac8cf409c000e3a2d3774"

        def install
          bin.install "cipherCode"
        end
      end
    end
  end
end
