# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ciphercode < Formula
  desc ""
  homepage "https://github.com/Lachignol/cipherCode-cli"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/Lachignol/cipherCode-cli/releases/download/v0.2.0/cipherCode-cli_Darwin_x86_64.tar.gz"
      sha256 "5b3f421d8cb60a1d9b26bd9db0b2cdfaef7f24f10c07fd503ee6ea333d705678"

      def install
        bin.install "cipherCode-cli"
      end
    end
    on_arm do
      url "https://github.com/Lachignol/cipherCode-cli/releases/download/v0.2.0/cipherCode-cli_Darwin_arm64.tar.gz"
      sha256 "de3906c8a17cc07f0a3887b20ac4ac36d3e50095229f58fe5bb5d658659ae0f5"

      def install
        bin.install "cipherCode-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode-cli/releases/download/v0.2.0/cipherCode-cli_Linux_x86_64.tar.gz"
        sha256 "c8763533a6821b07338e70b2b3a2205293d595991b6664f770747023f9cb8cc5"

        def install
          bin.install "cipherCode-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode-cli/releases/download/v0.2.0/cipherCode-cli_Linux_arm64.tar.gz"
        sha256 "f485ba78e577473e3f568b6ec08346e76975681d83479ba6b26a00d5123222ed"

        def install
          bin.install "cipherCode-cli"
        end
      end
    end
  end
end
