# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ciphercode < Formula
  desc ""
  homepage "https://github.com/Lachignol/cipherCode"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Darwin_x86_64.tar.gz"
      sha256 "58dd45812f5c4337e06b36c2a45f1a8d80c2b90dc89d515b6738585b7f05fa25"

      def install
        bin.install "cipherCode"
      end
    end
    on_arm do
      url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Darwin_arm64.tar.gz"
      sha256 "c421dfcc6b08df0738efd5616fb21a433cde99b522cf90f92263b44126917f92"

      def install
        bin.install "cipherCode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Linux_x86_64.tar.gz"
        sha256 "abc8e12bce9993edc49ab4a85f6c37867dc266491b352f605b24b98779b6d166"

        def install
          bin.install "cipherCode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/cipherCode/releases/download/v0.1.0/cipherCode_Linux_arm64.tar.gz"
        sha256 "2996b1486855c66433725420eeee84e4d71b1c98b1d195cbf1d1e60637620271"

        def install
          bin.install "cipherCode"
        end
      end
    end
  end
end
