# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MartinSolving < Formula
  desc ""
  homepage "https://github.com/Lachignol/martin-solving"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_x86_64.tar.gz"
      sha256 "add975be731895a549bb3c4a65c9d27bdfdfaaf81b4dbe6603fcd9baf42876bd"

      def install
        bin.install "martin-solving"
      end
    end
    on_arm do
      url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_arm64.tar.gz"
      sha256 "4212ad40d1924f1d017dac438f068a2e65c28a91ac13b881c8349f6c4688fc50"

      def install
        bin.install "martin-solving"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Linux_x86_64.tar.gz"
        sha256 "53a44ccd7cb6fb0358d6dee2b877604c9218ff5bd5fea0c85e5b72d6949e6621"

        def install
          bin.install "martin-solving"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Linux_arm64.tar.gz"
        sha256 "45a83f7c5cb404efa4f5cc331aa2e9e88699e5f894ae7574542f116791558003"

        def install
          bin.install "martin-solving"
        end
      end
    end
  end
end
