# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MartinSolving < Formula
  desc ""
  homepage "https://github.com/Lachignol/martin-solving"
  version "0.1.0"
  depends_on :macos

  on_intel do
    url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_x86_64.tar.gz"
    sha256 "76b748f0a26b19c5061428ed4ccd739c435476c5f7c18e9bada608419bb23b98"

    def install
      bin.install "martin-solving"
    end
  end
  on_arm do
    url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_arm64.tar.gz"
    sha256 "c6fa135685fab8f8418d597a20a4b92830364f09a9033ad34ebd40c1c1b0185b"

    def install
      bin.install "martin-solving"
    end
  end
end
