# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MartinSolving < Formula
  desc ""
  homepage "https://github.com/Lachignol/martin-solving"
  version "0.1.0"
  depends_on :macos

  on_intel do
    url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_x86_64.tar.gz"
    sha256 "1debfe10ba375be3275ffb4ecf271b6c2251f44b0a6403eca0f1d427e9fb4b99"

    def install
      bin.install "martin-solving"
    end
  end
  on_arm do
    url "https://github.com/Lachignol/martin-solving/releases/download/v0.1.0/martin-solving_Darwin_arm64.tar.gz"
    sha256 "1678913936dea7a2615a219e8de0239f001bca6e8b075d991240a5f33dfea608"

    def install
      bin.install "martin-solving"
    end
  end
end
